### ISSUE TITLE
After updating to 0.28.1 receiving java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by FoRRestDp** [JetBrains/Exposed#1073]
I have simple `IntIdTable`:
```kotlin
object Items : IntIdTable() {
  override val primaryKey = PrimaryKey(id)
  val category = reference("category", Categories)
  val name: Column<String> = varchar("name", 200)
  val description: Column<String?> = text("description").nullable()
  val imageLink: Column<String?> = varchar("img", 200).nullable()
  val price: Column<BigDecimal?> = decimal("price", 9, 2).nullable()
  val isHidden: Column<Boolean> = bool("hide").default(false)
}
```
and simple query:
```kotlin
transaction {
  Items.selectAll()
}
```
This query works fine while using library version 0.27.1,  but after updating to version 0.28.1 it throws `Exception in thread "main" java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.PropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'`.

I use PostgreSQL and Kotlin version 1.4.10

**Comment by Tapac** [comment]
Could you please provide the whole stack trace?

**Comment by FoRRestDp** [comment]
`Exception in thread "main" java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.PropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'
	at org.jetbrains.exposed.dao.EntityCacheKt.<clinit>(EntityCache.kt)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeRollback(EntityLifecycleInterceptor.kt:47)
	at org.jetbrains.exposed.sql.Transaction.rollback(Transaction.kt:72)
	at org.jetbrains.exposed.sql.transactions.TransactionApiKt.rollbackLoggingException(TransactionApi.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:191)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at MainKt.main(main.kt:40)
	at MainKt.main(main.kt)`

**Comment by FoRRestDp** [comment]
I should mention that there is `Item` entity in my project: 
```kotlin
class Item(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Item>(Items)
    var category by Category referencedOn Categories.id
    var name by Items.name
    var description by Items.description
    var img by Items.imageLink
    var price by Items.price
    var isHidden by Items.isHidden
    var owningUsers by User via UsersItems
}
```

**Comment by Tapac** [comment]
Do you have explicit `kotlin-reflect` dependency in your project? Could you check at it also has 1.4.10 version?

**Comment by FoRRestDp** [comment]
I didn't have it, but after adding I still get same exception

**Comment by Tapac** [comment]
Do you use java-time in your project? I found that it was built with Kotlin 1.3 as a target, maybe it is an issue.

**Comment by FoRRestDp** [comment]
No, but I use [PostgreSQL JDBC plugin](https://github.com/pgjdbc/pgjdbc), version 42.2.18 and [Kotlin Telegram Library](https://github.com/kotlin-telegram-bot/kotlin-telegram-bot) version 5.0.0 which is written for Kotlin 1.4.10

**Comment by FoRRestDp** [comment]
Also I use `java.math.BigDecimal` if that matters

**Comment by Tapac** [comment]
Is it possible to publish simple reproducable project somewhere? Otherwise I don't see any possibility to help you. 
Just gradle build file, Exposed mappings and main function which should fail with NoSuchMethodError.

**Comment by FoRRestDp** [comment]
Yep, here it is:
[](https://github.com/FoRRestDp/ExposedBugSampleProject)

It seem like the problem is related to [Kotlin Telegram Library](https://github.com/kotlin-telegram-bot/kotlin-telegram-bot). Before adding it to this project everything worked fine.

**Comment by Tapac** [comment]
Looks like you have the wrong telegram bot dependency.
It should be `implementation(group = "com.github.kotlin-telegram-bot.kotlin-telegram-bot", name = "telegram", version = "5.0.0")` instead of `implementation(group = "com.github.kotlin-telegram-bot", name = "kotlin-telegram-bot", version = "5.0.0")`

as the second one also includes all examples which comes with embedded 1.3.70 `kotlin-reflect` lib which overlaps with one from the Exposed.

**Comment by FoRRestDp** [comment]
Thank you, that helped. Closing issue
