### ISSUE TITLE
NoSuchMethodError after update

### ISSUE THREAD

**Issue by moeindev** [JetBrains/Exposed#959]
After updating from 0.24.1 to 0.25.1 I get this exception: 

`Exception in thread "main" java.lang.NoSuchMethodError: org.jetbrains.exposed.sql.Table.text$default(Lorg/jetbrains/exposed/sql/Table;Ljava/lang/String;Ljava/lang/String;ILjava/lang/Object;)Lorg/jetbrains/exposed/sql/Column;
	at data.dao.Users.<clinit>(Users.kt:6)
	at data.db.DataBaseUnit$initDB$1.invoke(DataBaseUnit.kt:24)
	at data.db.DataBaseUnit$initDB$1.invoke(DataBaseUnit.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at data.db.DataBaseUnit.initDB(DataBaseUnit.kt:21)
	at App$Companion.main(App.kt:9)
	at App.main(App.kt)`

here is the users table:

`object Users: IntIdTable() {
    val name = text("name")
    val family = text("family")
    val chatID = long("chat_id")
    val username = text("username")
}`

**Comment by ctan1345** [comment]
I had the same issue. It turns out I have multiple gradle projects and I only updated one of them.

Changing all the Exposed dependencies to the latest version resolved the issue for me.
